files:
  - source: /docs/localization/*.md
    translation: /%original_path%/%original_file_name%.%file_extension%
  - source: /docs/localization/*.mdx
    translation: /%original_path%/%original_file_name%.%file_extension%