files:
  - source: /docs/localization/*.md
    translation: /%original_path%/%two_letters_code%.%file_extension%
  - source: /docs/localization/*.mdx
    translation: /%original_path%/%two_letters_code%.%file_extension%
