name: Get Feedback on AI Reviewer

on:
  issue_comment:
    types: [edited]

jobs:
  detect-comment-edit:
    if: github.event.comment.user.login == 'github-actions[bot]' && github.event.comment.user.login != github.event.sender.login
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Checar se o comentário contém o feedback e detectar a resposta
      id: check_comment
      env:
        PR_NUMBER: ${{ github.event.issue.number }}
        COMMENT_BODY: ${{ github.event.comment.body }}
        USER: ${{ github.event.sender.login }}
        COMMENT_URL: ${{ github.event.comment.html_url }}
      run: |
        pip install requests
        python -m scripts.get_feedback
      
